config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'choice', to: 'alcohol_choices#new'
  get 'result', to: 'snacks#result'
  get 'mypage', to: 'mypages#show'
  resources :users, only: %i[new create]
  resources :mypages, only: %i[show edit update] do
    collection do
      get 'bookmarks', to: 'mypages#bookmark'
      get 'reviews', to: 'mypages#review'
    end
  end
  resources :password_resets, only: %i[new create edit update]
  resource :inquiry, only: %i[new create]
  resources :snacks, only: %i[show index] do
    resources :reviews, only: %i[create edit update destroy], shallow: true
    resource :bookmarks, only: %i[create destroy]
    collection do
      get 'wine', to: 'snacks#wine'
      get 'beer', to: 'snacks#beer'
      get 'sake', to: 'snacks#sake'
    end
  end

  namespace :admin do
    root 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :snacks do
      resources :reviews, shallow: true, only: %i[destroy]
    end
    resources :tags
    resources :users, only:%i[index edit update destroy]
    resources :inquiries, only:%i[index destroy]
  end

  # mailer
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/controllers/alcohol_choices_controller.rb
class AlcoholChoicesController < ApplicationController
  def new; end
end

app/views/alcohol_choices/new.html.erb
<% content_for(:title, "ぴったりのおつまみを探す") %>
<% cache do %>
<%= image_tag "header_awa.png", class: "headerimage" %>
  <div class="card-img-overlay">
    <div class="container">
      <h1 class="font-weight-bold title-font">飲みたいお酒は？</h1>
    </div>
  </div>
  <div class="container alcohol-container">
    <div class="wrapper">
      <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
        <div class="justify-content-center"> 
          <div class='text-center'>
            <div class="alcohol_choice">
              <%= link_to beer_snacks_path do %>
                <%= image_pack_tag "media/images/beer.png", size: "250x250", class: 'rounded-circle m-5 shadow-lg' %>
              <% end %>
              <%= link_to wine_snacks_path do %>
                <%= image_pack_tag "media/images/wine.png", size: "250x250", class: 'rounded-circle m-5 shadow-lg' %>
              <% end %>
              <%= link_to sake_snacks_path do %>
                <%= image_pack_tag "media/images/sake.png", size: "250x250", class: 'rounded-circle m-5 shadow-lg p-1 mb-5 bg-info rounded' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>