config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'choice', to: 'alcohol_choices#new'
  get 'result', to: 'snacks#result'
  get 'mypage', to: 'mypages#show'
  resources :users, only: %i[new create]
  resources :mypages, only: %i[show edit update] do
    collection do
      get 'bookmarks', to: 'mypages#bookmark'
      get 'reviews', to: 'mypages#review'
    end
  end
  resources :password_resets, only: %i[new create edit update]
  resource :inquiry, only: %i[new create]
  resources :snacks, only: %i[show index] do
    resources :reviews, only: %i[create edit update destroy], shallow: true
    resource :bookmarks, only: %i[create destroy]
    collection do
      get 'wine', to: 'snacks#wine'
      get 'beer', to: 'snacks#beer'
      get 'sake', to: 'snacks#sake'
    end
  end

  namespace :admin do
    root 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :snacks do
      resources :reviews, shallow: true, only: %i[destroy]
    end
    resources :tags
    resources :users, only:%i[index edit update destroy]
    resources :inquiries, only:%i[index destroy]
  end

  # mailer
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/shared/_error_messages.html.erb
<div id="error_messages">
<% if model.errors.any? %>
    <div class="text-danger">
      <% model.errors.full_messages_for(attribute).each do |msg| %>
        ※ <%= msg %>
      <% end %>
    </div>
<% end %>
</div>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-muted py-3 bg-dark w-100" id="footer">
  <div class="container">
    <div class="text-center">
      <div class="row">
        <div class="col">
          <%= link_to 'おつまみこ', root_path, class: "footer-logo text-decoration-none" %>
        </div>
        <div class="col">
          <%= link_to 'プライバシー', privacy_path, class: "footer-text text-decoration-none" %>
        </div>
        <div class="col">
          <%= link_to '利用規約', terms_path, class: "footer-text text-decoration-none" %>
        </div>
        <div class="col">
          <%= link_to 'お問い合わせ', new_inquiry_path, class: "footer-text text-decoration-none" %>
        </div>
        <div class="col-1">
          <%= link_to "https://twitter.com/otsumamiko25", class: "footer-text text-decoration-none", target: :_blank, rel: 'noopener noreferrer' do %>
            <i class="fab fa-twitter"></i>
          <% end %>
        </div>
        <div class="col-12">
          <p>©️ 2021 おつまみこ</p>
        </div>
      </div>
    </div>
  </div>
</footer>

<%= javascript_pack_tag "pages/footer", defer: true %>

app/views/shared/_header.html.erb
<header>
<%= link_to root_path do %>
  <%= image_tag "logo-min.png", size: "150x150", class: "header-logo" %>
<% end %>
<div id="nav-toggle">
  <div>
    <span></span>
    <span></span>
    <span></span>
  </div>
</div>

<div id="gloval-nav">
  <nav>
    <ul>
      <li><%= link_to 'おつまみでお困りの方', choice_path, class: "header-nav-link" %></li>
      <li><%= link_to 'おつまみ一覧', snacks_path, class: "header-nav-link" %></li>
      <li><%= link_to 'マイページ', mypage_path, class: "header-nav-link" %></li>
      <li><%= link_to 'お気に入り', bookmarks_mypages_path, class: "header-nav-link" %></li>
      <li><%= link_to 'レビュー', reviews_mypages_path, class: "header-nav-link" %></li>
      <li><%= link_to 'ログアウト', logout_path, method: :delete, class: "header-nav-link" %></li>
    </ul>
  </nav>
</div>
</header>

<%= javascript_pack_tag "pages/header", defer: true %>

app/views/shared/_next_link.html.erb
<div class="h3 text-center mb-5">
<%== pagy_next_link(@pagy, '', 'id="next_link" style="display: none;"') %>
</div>

app/views/shared/_not_logged_in_header.html.erb
<header>
<%= link_to root_path do %>
  <%= image_tag "logo-min.png", size: "150x150", class: "header-logo" %>
<% end %>
<div id="nav-toggle">
  <div>
    <span></span>
    <span></span>
    <span></span>
  </div>
</div>

<div id="gloval-nav">
  <nav>
    <ul>
      <li><%= link_to 'おつまみでお困りの方', choice_path, class: "header-nav-link" %></li>
      <li><%= link_to 'おつまみ一覧', snacks_path, class: "header-nav-link" %></li>
      <li><%= link_to 'ログイン', login_path, class: "header-nav-link" %></li>
    </ul>
  </nav>
</div>
</header>

<%= javascript_pack_tag "pages/header", defer: true %>