config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'choice', to: 'alcohol_choices#new'
  get 'result', to: 'snacks#result'
  get 'mypage', to: 'mypages#show'
  resources :users, only: %i[new create]
  resources :mypages, only: %i[show edit update] do
    collection do
      get 'bookmarks', to: 'mypages#bookmark'
      get 'reviews', to: 'mypages#review'
    end
  end
  resources :password_resets, only: %i[new create edit update]
  resource :inquiry, only: %i[new create]
  resources :snacks, only: %i[show index] do
    resources :reviews, only: %i[create edit update destroy], shallow: true
    resource :bookmarks, only: %i[create destroy]
    collection do
      get 'wine', to: 'snacks#wine'
      get 'beer', to: 'snacks#beer'
      get 'sake', to: 'snacks#sake'
    end
  end

  namespace :admin do
    root 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :snacks do
      resources :reviews, shallow: true, only: %i[destroy]
    end
    resources :tags
    resources :users, only:%i[index edit update destroy]
    resources :inquiries, only:%i[index destroy]
  end

  # mailer
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/snack.rb
class Snack < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :tag_relationships, dependent: :destroy
  has_many :tags, through: :tag_relationships
  has_many :reviews, dependent: :destroy
  has_one_attached :image
  validates :name, uniqueness: { case_sensitive: true }, presence: true
  validates :alcohol, presence: true
  enum alcohol: { beer: 0, wine: 1, sake: 2 }

  scope :name_contain, ->(name) { where('snacks.name LIKE ?', "%#{name}%") }
end

app/controllers/admin/snacks_controller.rb
class Admin::SnacksController < Admin::BaseController
  include Pagy::Backend
  before_action :set_snack, only: %i[show edit update destroy]
  def new
    @snack = Snack.new
  end

  def create
    @snack = Snack.new(snack_params)

    if @snack.save
      redirect_to new_admin_snack_path, success: "おつまみを追加しました"
    else
      flash.now[:danger] = "おつまみを追加に失敗しました"
      render :new
    end
  end
  
  def index
    @pagy, @snacks = pagy(Snack.all.includes(:tags, :reviews, :bookmarks, { image_attachment: :blob }))
  end

  def show
    @reviews = @snack.reviews
  end

  def edit; end

  def update
    if @snack.update(snack_params)
      redirect_to admin_snack_path(@snack), success: "更新に成功しました"
    else
      flash.now[:danger] = "更新に失敗しました"
      render :edit
    end
  end

  def destroy
    @snack.image.purge if @snack.image.attached?
    @snack.destroy!
  end

  private

  def snack_params
    params.require(:snack).permit(:name, :alcohol, :image, tag_ids: [])
  end

  def set_snack
    @snack = Snack.find(params[:id])
  end
end

app/controllers/snacks_controller.rb
class SnacksController < ApplicationController
  include ActiveModel::Model
  include ActiveModel::Attributes
  include Pagy::Backend
  
  def show
    @snack = Snack.find(params[:id])
    @review = Review.new
    @reviews = @snack.reviews.includes(:user).order(created_at: :desc)
    if @snack.reviews.blank?
      @snack_rate = 0.0
    else
      @snack_rate = @snack.reviews.average(:rate).round(2)
    end
  end

  def index
    @search_snacks_form = SearchSnacksForm.new(search_params)
    @pagy, @snack = pagy_countless(@search_snacks_form.search.includes(:reviews, { image_attachment: :blob }), link_extra: 'data-remote="true"')

    @tags = Tag.all

    if @pagy.page == @pagy.pages
      @next_page = "last"
    else
      @next_page = @pagy.page
    end
  end

  def result
    tag_ids = params[:tag]
    alcohol = params[:alcohol]
    match_tags = TagRelationship.by_tag(tag_ids).group_snack_id.having_count(tag_ids)
    snack_ids = match_tags.map(&:snack_id)
    @snack = Snack.where(id: snack_ids, alcohol: alcohol).sample
    @review = Review.new
    @reviews = @snack.reviews.includes(:user).order(created_at: :desc)
    if @snack.reviews.blank?
      @snack_rate = 0.0
    else
      @snack_rate = @snack.reviews.average(:rate).round(2)
    end
  end

  private
  
  def snack_params
    params.require(:snack).permit(:name, :alcohol, :image)
  end

  def search_params
    params[:q]&.permit(:name, :alcohol, tag_ids: [])
  end
end

app/views/admin/snacks/_snack.html.erb
<tr class="text-center">
  <td><%= snack.id %></td>
  <td><%= snack.image.attached? %></td>
  <td><%= link_to snack.name, admin_snack_path(snack), method: :get %></td>
  <td><%= snack.alcohol_i18n %></td>
  <td><%= snack.tags.pluck(:name).join(', ') %></td>
  <td><%= snack.bookmarks.length %></td>
  <td><%= snack.reviews.length %></td>
  <td>
    <ul>
      <li class='list-inline-item'>
        <%= button_to "編集", edit_admin_snack_path(snack), method: :get, class: "btn btn-danger" %>
      </li>
      <li class='list-inline-item'>
        <%= button_to "削除", admin_snack_path(snack), method: :delete, data: { confirm: '本当に削除してもよろしいですか？'}, class: "btn btn-secondary" %>
      </li>
    </ul>
  </td>
</tr>

app/views/admin/snacks/edit.html.erb
<h1 class="text-center my-5">おつまみ編集</h1>
<div class="row justify-content-center text-center">
  <div class="col-8">
    <div class="card text-center">
      <div class="card-body">
      <%= form_with model: @snack, url: admin_snack_path(@snack), method: :patch, local: true do |f| %>
        <div class="form-group">
          <%= f.label :image, class: "text-info" %>
          <%= f.file_field :image, value: @snack.image, accept: 'image/*', class: "form-control" %>
          <%= render 'shared/error_messages', model: f.object, attribute: :image %>
        </div>
        <div class="form-group">
          <%= f.label :name, class: "text-info" %>
          <%= f.text_field :name, value: @snack.name, class: "form-control" %>
          <%= render 'shared/error_messages', model: f.object, attribute: :name %>
        </div>
        <div class="form-group">
          <%= f.label :alcohol, class: "text-info" %><br>
          <%= f.select :alcohol, Snack.alcohols.keys.map {|k| [I18n.t("enums.snack.alcohol.#{k}"), k]}, class: "form-control" %>
          <%= render 'shared/error_messages', model: f.object, attribute: :alcohol %>
        </div>
        <div class="check_box" >
          <%= f.label :tag, class: "text-info" %><br>
          <%= collection_check_boxes(:snack, :tag_ids, Tag.all, :id, :name, include_hidden: false) do |tag| %>
          <%= tag.label { tag.check_box + tag.text } %>
          <% end %>
          <%= render 'shared/error_messages', model: f.object, attribute: :tag %>
        </div>
        <div class="actions text-center">
          <%= f.submit "送信", class: "btn btn-primary" %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/snacks/index.html.erb
<h1 class="text-center my-1">おつまみ一覧</h1>
<div class="text-right">
  <%= link_to "新規作成", new_admin_snack_path %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col" class="text-center">id</th>
      <th scope="col" class="text-center">image</th>
      <th scope="col" class="text-center">name</th>
      <th scope="col" class="text-center">alcohol</th>
      <th scope="col" class="text-center">tag</th>
      <th scope="col" class="text-center">bookmark</th>
      <th scope="col" class="text-center">review</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <%= render @snacks %>
  </tbody>
</table>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/admin/snacks/new.html.erb
<h1 class="text-center my-5">新規作成</h1>
<div class="row justify-content-center text-center">
  <div class="col-8">
    <div class="card text-center">
      <div class="card-body">
      <%= form_with model: @snack, url: admin_snacks_path, local: true, method: :post do |f| %>
        <div class="form-group">
          <%= f.label :image, class: "text-info" %>
          <%= f.file_field :image, accept: 'image/*', class: "form-control" %>
          <%= render 'shared/error_messages', model: f.object, attribute: :image %>
        </div>
        <div class="form-group">
          <%= f.label :name, class: "text-info" %>
          <%= f.text_field :name, class: "form-control" %>
          <%= render 'shared/error_messages', model: f.object, attribute: :name %>
        </div>
        <div class="form-group">
          <%= f.label :alcohol, class: "text-info" %><br>
          <%= f.select :alcohol, Snack.alcohols.keys.map {|k| [I18n.t("enums.snack.alcohol.#{k}"), k]}, class: "form-control" %>
          <%= render 'shared/error_messages', model: f.object, attribute: :alcohol %>
        </div>
        <div class="check_box" >
          <%= f.label :tag, class: "text-info" %><br>
          <%= collection_check_boxes(:snack, :tag_ids, Tag.all, :id, :name, include_hidden: false) do |tag| %>
            <%= tag.label { tag.check_box + tag.text } %>
          <% end %>
          <%= render 'shared/error_messages', model: f.object, attribute: :tag %>
        </div>
        <div class="actions">
          <%= f.submit '送信', class: "btn btn-primary" %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/snacks/show.html.erb
<h1 class="text-center my-5">おつまみ詳細</h1>
<div class="row justify-content-center text-center">
  <div class="col-8">
    <div class="card text-center">
      <div class="card-body">
        <h5 class="py-3 text-info">Image</h5>
        <% if @snack.image.attached? %>
          <%= image_tag @snack.image, size: "300x300" %>
        <% end %>

        <h5 class="text-info">Name</h5>
          <%= @snack.name %>

        <h5 class="text-info">Alcohol</h5>
          <%= @snack.alcohol_i18n %>
          
        <h5 class="text-info">Tag</h5>
          <%= @snack.tags.pluck(:name).join(', ') %>
      </div>
    </div>
    <ul>
      <li class='list-inline-item'>
        <%= button_to "編集", edit_admin_snack_path(@snack), method: :get, class: "btn btn-danger" %>
      </li>
      <li class='list-inline-item'>
        <%= button_to "削除", admin_snack_path(@snack), method: :delete, data: { confirm: '本当に削除してもよろしいですか？'}, class: "btn btn-secondary" %>
      </li>
    </ul>
  </div>
</div>
  <h5 class="text-info text-center">Review</h5>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col" class="text-center">id</th>
      <th scope="col" class="text-center">name</th>
      <th scope="col" class="text-center">comment</th>
      <th scope="col" class="text-center">rate</th>
      <th scope="col" class="text-center">sweetness</th>
      <th scope="col" class="text-center">salty</th>
      <th scope="col" class="text-center">acidity</th>
      <th scope="col" class="text-center">taste</th>
      <th scope="col" class="text-center">scent</th>
      <th scope="col" class="text-center">created_at</th>
      <th scope="col" class="text-center">updated_at</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <%= render @reviews %>
  </tbody>
</table>
  