config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'choice', to: 'alcohol_choices#new'
  get 'result', to: 'snacks#result'
  get 'mypage', to: 'mypages#show'
  resources :users, only: %i[new create]
  resources :mypages, only: %i[show edit update] do
    collection do
      get 'bookmarks', to: 'mypages#bookmark'
      get 'reviews', to: 'mypages#review'
    end
  end
  resources :password_resets, only: %i[new create edit update]
  resource :inquiry, only: %i[new create]
  resources :snacks, only: %i[show index] do
    resources :reviews, only: %i[create edit update destroy], shallow: true
    resource :bookmarks, only: %i[create destroy]
    collection do
      get 'wine', to: 'snacks#wine'
      get 'beer', to: 'snacks#beer'
      get 'sake', to: 'snacks#sake'
    end
  end

  namespace :admin do
    root 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :snacks do
      resources :reviews, shallow: true, only: %i[destroy]
    end
    resources :tags
    resources :users, only:%i[index edit update destroy]
    resources :inquiries, only:%i[index destroy]
  end

  # mailer
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarks_snacks, through: :bookmarks, source: :snack
  has_many :reviews, dependent: :destroy
  has_many :reviews_snacks, through: :reviews, source: :snack
  authenticates_with_sorcery!
  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :name, presence: true, length: { maximum: 10 }
  validates :email, uniqueness: { case_sensitive:  true }, presence: true
  validates :reset_password_token, presence: true, uniqueness: true, allow_nil: true

  enum role: { general: 0, admin: 1 }

  def bookmark(snack)
    bookmarks_snacks << snack
  end

  def unbookmark(snack)
    bookmarks_snacks.destroy(snack)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  include Pagy::Backend
  before_action :set_user, only: %i[edit update destroy]
  def index
    @pagy, @users = pagy(User.all)
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, success: "ユーザー情報を変更しました"
    else
      flash.now[:danger] = "ユーザー情報を変更できませんでした"
      render :edit
    end
  end

  def destroy
    @user.destroy!
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Pagy::Backend

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      flash[:notice] = 'ようこそ！'
      redirect_to root_path
    else
      flash[:alert] = '登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/views/admin/users/_user.html.erb
<tr class="text-center">
  <td><%= user.id %></td>
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= user.role_i18n %></td>
  <td><%= user.created_at.strftime('%Y/%m/%d') %></td>
  <td>
    <ul>
      <li class='list-inline-item'>
        <%= button_to "編集", edit_admin_user_path(user), method: :get, class: "btn btn-danger" %>
      </li>
      <li class='list-inline-item'>
        <%= button_to "削除", admin_user_path(user), method: :delete, data: { confirm: '本当に削除してもよろしいですか？'}, class: "btn btn-secondary" %>
      </li>
    </ul>
  </td>
</tr>

app/views/admin/users/edit.html.erb
<h1 class="text-center my-5">ユーザー編集</h1>
<div class="row justify-content-center text-center">
  <div class="col-8">
    <div class="card text-center">
      <div class="card-body">
      <%= form_with model: @user, url: admin_user_path(@user), local: true, method: :patch do |f| %>
        <div class="form-group">
          <%= f.label :name, class: "text-info" %>
          <%= f.text_field :name, value: @user.name, class: "form-control" %>
          <%= render 'shared/error_messages', model: f.object, attribute: :name %>
        </div>
        <div class="form-group">
          <%= f.label :email, class: "text-info" %>
          <%= f.text_field :email, value: @user.email, class: "form-control" %>
          <%= render 'shared/error_messages', model: f.object, attribute: :email %>
        </div>
        <div class="form-group">
          <%= f.label :role, class: "text-info" %>
          <%= f.select :role, User.roles.keys.map {|k| [I18n.t("enums.user.role.#{k}"), k]}, class: "form-control" %>
          <%= render 'shared/error_messages', model: f.object, attribute: :role %>
        </div>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<h1 class="text-center my-1">ユーザー一覧</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col" class="text-center">id</th>
      <th scope="col" class="text-center">name</th>
      <th scope="col" class="text-center">email</th>
      <th scope="col" class="text-center">role</th>
      <th scope="col" class="text-center">created_at</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <%= render @users %>
  </tbody>
</table>
<%== pagy_bootstrap_nav(@pagy) %>